#
# |__  $$__/                                    | $$              | $$              | $$  / $$
#    | $$  /$$$$$$  /$$$$$$  /$$$$$$$    /$$$$$$$| $$  /$$$$$$  /$$$$$$    /$$$$$$ | $$/$$/
#    | $$ /$$__  $$|____  $$| $$__  $$  /$$_____/| $$ |____  $$|_  $$_/   /$$__  $$ \ $$$$/
#    | $$| $$  \__/ /$$$$$$$| $$  \ $$ | $$$$$$  | $$  /$$$$$$$  | $$    | $$$$$$$$ $$  $$
#    | $$| $$      /$$__  $$| $$  | $$  \____  $$| $$ /$$__  $$  | $$ /$$| $$_____/ /$$/\ $$
#    | $$| $$     |  $$$$$$$| $$  | $$ / $$$$$$$/| $$|  $$$$$$$  |  $$$$/|  $$$$$$$| $$  \ $$
#    |__/|__/      \_______/|__/  |__/ |_______/ |__/ \_______/   \___/   \_______/|__/  |__/
#
# Description: TranslateX is a plugin that allows you to translate messages and items in your server.
# Author: Djorr (Rubix Development)
# Version: 1.0.0
# Discord: https://discord.rubixdevelopment.nl/
#

# ========================================
# GENERAL SETTINGS
# ========================================
GENERAL:
  # Enable/disable the plugin
  enabled: true
  
  # Default language for the server
  default_language: "EN"
  
  # Enable debug mode
  debug: false
  
  # Maximum message length for translation
  max_message_length: 1000
  
  # Translation cache duration in minutes
  cache_duration: 30

# ========================================
# TRANSLATION PROVIDERS
# ========================================
TRANSLATION_PROVIDERS:
  # OpenAI API Configuration
  openai:
    enabled: true
    api_keys:
      - "<YOUR_OPENAI_API_KEY>"
    # OpenAI specific settings
    model: "gpt-3.5-turbo"
    max_tokens: 150
    temperature: 0.3

# ========================================
# FEATURES
# ========================================
FEATURES:
  # Chat translation
  chat_translation:
    enabled: true
    # Auto-translate incoming chat messages
    auto_translate_incoming: true
    # Show original message alongside translation
    show_original: true
  
  # Item translation
  item_translation:
    enabled: true
    # Translate item names
    translate_names: true
    # Translate item lore
    translate_lore: true

# ========================================
# PERFORMANCE
# ========================================
PERFORMANCE:
  # Caching
  caching:
    enabled: true
    # Cache size limit
    max_cache_size: 10000
    # Cache expiration time in minutes
    expiration_time: 60
  
  # Async processing
  async:
    enabled: true
    # Thread pool size
    thread_pool_size: 4

# ========================================
# MESSAGES
# ========================================
MESSAGES:
  prefix: "&6&lTranslateX &8» &f"
  language_set: "&aYour language has been set to: {language} ({code})"
  translation_success: "&aMessage translated successfully!"
  translation_failed: "&cTranslation failed. Please try again."
  no_permission: "&cYou don't have permission to use this command."
  invalid_language: "&cInvalid language specified."

# ========================================
# PERMISSIONS
# ========================================
PERMISSIONS:
  # Basic translation permission
  translate: "translatorx.translate"
  # Item translation permission
  translate_items: "translatorx.translate.items"
  # Admin permission
  admin: "translatorx.admin"
  # Bypass rate limit permission
  bypass_rate_limit: "translatorx.bypass.ratelimit"