#
# |__  $$__/                                    | $$              | $$              | $$  / $$
#    | $$  /$$$$$$  /$$$$$$  /$$$$$$$    /$$$$$$$| $$  /$$$$$$  /$$$$$$    /$$$$$$ | $$/$$/
#    | $$ /$$__  $$|____  $$| $$__  $$  /$$_____/| $$ |____  $$|_  $$_/   /$$__  $$ \ $$$$/
#    | $$| $$  \__/ /$$$$$$$| $$  \ $$ | $$$$$$  | $$  /$$$$$$$  | $$    | $$$$$$$$ $$  $$
#    | $$| $$      /$$__  $$| $$  | $$  \____  $$| $$ /$$__  $$  | $$ /$$| $$_____/ /$$/\ $$
#    | $$| $$     |  $$$$$$$| $$  | $$ / $$$$$$$/| $$|  $$$$$$$  |  $$$$/|  $$$$$$$| $$  \ $$
#    |__/|__/      \_______/|__/  |__/ |_______/ |__/ \_______/   \___/   \_______/|__/  |__/
#
# Description: TranslateX is a plugin that allows you to translate messages in your server.
# Author: Djorr (Rubix Development)
# Version: 0.5-BETA
# Discord: https://discord.rubixdevelopment.nl/
#
API_KEYS:
  - "<YOUR DEEPL API KEY>"