name: TranslateX
version: '${project.version}'
main: xyz.aizsargs.translate.TranslateX
authors: [ PingLagger ]
commands:
  translator:
    description: Translate a message
    aliases: [ tr, t, translator, translate ]