name: TranslateX
version: '1.0.0'
main: nl.rubixdevelopment.translate.TranslateX
api-version: '1.13'
authors: [Djorr]
description: Advanced translation plugin with multi-API support for Folia, Paper, and Spigot servers
website: https://github.com/Rubix-Development/TranslateX
softdepend: [Vault]

# Server compatibility
# - Folia: 1.20.1+
# - Paper: 1.13+
# - Spigot: 1.8.8+

commands:
  translator:
    description: Main command for TranslateX plugin
    usage: /<command> [subcommand] [args]
    aliases: [t, translatorx, tx, lang]
    permission: translatorx.translate

permissions:
  translatorx.translate:
    description: Allows players to use basic translation features
    default: true
  translatorx.translate.items:
    description: Allows players to translate items
    default: true
  translatorx.admin:
    description: Allows access to admin commands
    default: op
  translatorx.bypass.ratelimit:
    description: Allows players to bypass rate limiting
    default: op